on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *"

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
          path: main
      - uses: actions/checkout@v7
        with:
          ref: live
          path: live
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.9.4
      - name: Run the main script
        run: deno run --allow-all main/main.js
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "main"
          git push
